<?php
	/*******************************
	 *	Project: Dang Lien Library
	 *	Start: 12:00 12/11/2015
	 *******************************/
	
	/******************************************
	 *
	 *	DO NOT EDIT THIS FILE
	 *
	 ******************************************/
	
	//start session
	session_start();
	
	//off error messenger
	error_reporting(0);//on = 1, off = 0

	//Define ROOT_ACCESS for security
	define("ROOT_ACCESS",true);
	
	//Global variable
	$GLOB;//input, vars, GET, POST, all data
	$DB;//database query
	$USER;//master_admin, admin, member
	$BOOK;//read, insert, delete, edit, buy
	$HTML = "";//All html output
	
	//Set: default time zone
	date_default_timezone_set("Asia/Ho_Chi_Minh");
	
	//test: uncomment next line
    //echo date('Y-m-d H:i:s');
	
	//load system file
	$core = "sys/init.php";
	if(file_exists($core)){
		require($core);
	}else{
		echo "System error!!!";exit;
	}
	print $HTML;
	exit;
	//request complete
?>